title = "Вело Клуб Мамут | Velo Club Mammut | Association Mammoth Cycling Club"
baseURL = "https://www.veloclubmammut.com"
languageCode = "bg-BG"
theme = "gohugo-theme-ananke"
themesDir = "themes"
resourceDir = "../resources"

DefaultContentLanguage = "bg"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[languages]
  [languages.bg]
    title = "За нас"
    weight = 2
    contentDir = "content/bg"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  author = ""
  favicon = ""
  site_logo = ""
  description = "Велоклуб Мамут"
  facebook = "https://www.facebook.com/veloclubmammut"
  twitter = ""
  instagram = ""
  youtube = ""
  github = "https://github.com/VeloclubMammut"
  gitlab = ""
  linkedin = ""
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "https://scontent.fsof9-1.fna.fbcdn.net/v/t39.30808-6/243836465_4506578852722204_984899014349558963_n.png?_nc_cat=110&ccb=1-5&_nc_sid=e3f864&_nc_ohc=Yd7Y7COuHTsAX9PyucP&_nc_ht=scontent.fsof9-1.fna&oh=8a1f54c1e0c9b560a5bc8fdf1bdafd21&oe=615CD65F"
  recent_posts_number = 2
